[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://paperplus-hugo-theme.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
