name = "PaperPlus"
license = "MIT"
licenselink = "https://github.com/mohnoor94/paperplus-hugo-theme/blob/master/LICENSE"
description = "A Hugo theme made with PaperCSS, the less formal CSS framework."
homepage = "https://github.com/mohnoor94/paperplus-hugo-theme"
tags = ["blog", "paper", "informal"]
features = ["blog", "toc", "shortcodes"]
min_version = "0.60.1"

[author]
  name = "Mohammad Noor AbuKhleif"
  homepage = "https://noor.guru/"
